# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
