# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clubs.Article'),
        ),
    ]
