# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='', verbose_name='C:\\Users\\usert\\django_tutorial\\mysite'),
        ),
    ]
