# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20160731_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='C:\\Users\\usert\\django_tutorial\\mysite\\myapp/static/'),
        ),
    ]
