# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20160731_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='', verbose_name='/static'),
        ),
    ]
